/*
 * Main.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class Main extends javax.swing.JFrame {

	/** Creates new form Main */
	public Main() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		AdminManage = new javax.swing.JMenu();
		OrgManage = new javax.swing.JMenu();
		OrgManager = new javax.swing.JMenuItem();
		DepManage = new javax.swing.JMenu();
		SpeManage = new javax.swing.JMenu();
		PersonManage = new javax.swing.JMenu();
		ActivityManage = new javax.swing.JMenu();
		ActivityManager = new javax.swing.JMenuItem();
		AttManage = new javax.swing.JMenu();
		AttManager = new javax.swing.JMenuItem();
		CheckInAndOut = new javax.swing.JMenuItem();
		RewardManage = new javax.swing.JMenu();
		RewardManager = new javax.swing.JMenuItem();
		StatisticsManage = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		AdminManage.setText("\u7ba1\u7406\u5458\u8bbe\u7f6e");
		jMenuBar1.add(AdminManage);

		OrgManage.setText("\u7ec4\u7ec7\u7ba1\u7406");

		OrgManager.setText("\u7ec4\u7ec7\u7ba1\u7406");
		OrgManager.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OrgManagerActionPerformed(evt);
			}
		});
		OrgManage.add(OrgManager);

		jMenuBar1.add(OrgManage);

		DepManage.setText("\u90e8\u95e8\u7ba1\u7406");
		jMenuBar1.add(DepManage);

		SpeManage.setText("\u4e13\u4e1a\u7ba1\u7406");
		jMenuBar1.add(SpeManage);

		PersonManage.setText("\u4eba\u5458\u7ba1\u7406");
		jMenuBar1.add(PersonManage);

		ActivityManage.setText("\u6d3b\u52a8\u7ba1\u7406");

		ActivityManager.setText("\u6d3b\u52a8\u7ba1\u7406");
		ActivityManager.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ActivityManagerActionPerformed(evt);
			}
		});
		ActivityManage.add(ActivityManager);

		jMenuBar1.add(ActivityManage);

		AttManage.setText("\u8003\u52e4\u7ba1\u7406");

		AttManager.setText("\u8003\u52e4\u7ba1\u7406");
		AttManager.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AttManagerActionPerformed(evt);
			}
		});
		AttManage.add(AttManager);

		CheckInAndOut.setText("\u7b7e\u5230\u7b7e\u9000");
		CheckInAndOut.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CheckInAndOutActionPerformed(evt);
			}
		});
		AttManage.add(CheckInAndOut);

		jMenuBar1.add(AttManage);

		RewardManage.setText("\u5956\u60e9\u7ba1\u7406");

		RewardManager.setText("\u5956\u60e9\u7ba1\u7406");
		RewardManager.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RewardManagerActionPerformed(evt);
			}
		});
		RewardManage.add(RewardManager);

		jMenuBar1.add(RewardManage);

		StatisticsManage.setText("\u7edf\u8ba1\u4fe1\u606f");
		jMenuBar1.add(StatisticsManage);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jDesktopPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 680,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void CheckInAndOutActionPerformed(java.awt.event.ActionEvent evt) {
		CheckInAndOutManager checkInAndOutManager = new CheckInAndOutManager();
		checkInAndOutManager.setClosable(true);
		checkInAndOutManager.setClosable(true);
		checkInAndOutManager.setVisible(true);
		this.jDesktopPane1.add(checkInAndOutManager);
		checkInAndOutManager.toFront();
	}

	private void RewardManagerActionPerformed(java.awt.event.ActionEvent evt) {
		RewardManager rewardManager = new RewardManager();
		rewardManager.setClosable(true);
		rewardManager.setVisible(true);
		this.jDesktopPane1.add(rewardManager);
		rewardManager.toFront();
	}

	private void AttManagerActionPerformed(java.awt.event.ActionEvent evt) {
		AttManager attManager = new AttManager();
		attManager.setClosable(true);
		attManager.setVisible(true);
		this.jDesktopPane1.add(attManager);
		attManager.toFront();
	}

	private void ActivityManagerActionPerformed(java.awt.event.ActionEvent evt) {
		ActivityManager activityManager = new ActivityManager();
		activityManager.setClosable(true);
		activityManager.setVisible(true);
		this.jDesktopPane1.add(activityManager);
		activityManager.toFront();
	}

	private void OrgManagerActionPerformed(java.awt.event.ActionEvent evt) {
		OrgManager orgManager = new OrgManager();
		orgManager.setClosable(true);
		orgManager.setVisible(true);
		this.jDesktopPane1.add(orgManager);
		orgManager.toFront();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu ActivityManage;
	private javax.swing.JMenuItem ActivityManager;
	private javax.swing.JMenu AdminManage;
	private javax.swing.JMenu AttManage;
	private javax.swing.JMenuItem AttManager;
	private javax.swing.JMenuItem CheckInAndOut;
	private javax.swing.JMenu DepManage;
	private javax.swing.JMenu OrgManage;
	private javax.swing.JMenuItem OrgManager;
	private javax.swing.JMenu PersonManage;
	private javax.swing.JMenu RewardManage;
	private javax.swing.JMenuItem RewardManager;
	private javax.swing.JMenu SpeManage;
	private javax.swing.JMenu StatisticsManage;
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JMenuBar jMenuBar1;
	// End of variables declaration//GEN-END:variables

}