package ls.Frame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import other.wzbcOrg.AdminLogin;
import other.wzbcOrg.OpenSituation;
import other.wzbcOrg.OtherFunction;
import other.wzbcOrg.SHA1;
import other.wzbcOrg.SqlFunction;

/*
 * AdminManage.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class AdminManage extends javax.swing.JInternalFrame {
	SqlFunction sqlFunction = new SqlFunction();
	OtherFunction otherFunction = new OtherFunction();
	String oldName = "";

	/** Creates new form AdminManage */
	public AdminManage() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();

		addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			public void internalFrameActivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosed(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameClosed(evt);
			}

			public void internalFrameClosing(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeactivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeiconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameIconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameOpened(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameOpened(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "用户名", "密码", "权限等级", "所属组织" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jLabel2.setText("\u5bc6    \u7801\uff1a");

		jLabel3.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");

		jLabel4.setText("\u7ba1\u7406\u5458\u7ea7\u522b\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"高级管理员", "学生管理员", "学生干事" }));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/add.png"))); // NOI18N
		jButton1.setText("\u6dfb\u52a0\u7ba1\u7406\u5458");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/refresh.png"))); // NOI18N
		jButton2.setText("\u4fee\u6539\u7ba1\u7406\u5458");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/close.png"))); // NOI18N
		jButton3.setText("\u5220\u9664\u7ba1\u7406\u5458");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox2.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox2ItemStateChanged(evt);
			}
		});

		jLabel5.setText("\u7ec4\u7ec7\u7b5b\u9009\uff1a");

		jLabel6.setText("\u6240\u5c5e\u7ec4\u7ec7\uff1a");

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(46, 46, 46)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				67,
																				67,
																				67)
																		.add(
																				jButton1)
																		.add(
																				64,
																				64,
																				64)
																		.add(
																				jButton2)
																		.add(
																				79,
																				79,
																				79)
																		.add(
																				jButton3)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				127,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.TRAILING,
																												false)
																										.add(
																												layout
																														.createSequentialGroup()
																														.add(
																																15,
																																15,
																																15)
																														.add(
																																layout
																																		.createParallelGroup(
																																				org.jdesktop.layout.GroupLayout.TRAILING)
																																		.add(
																																				jLabel3)
																																		.add(
																																				jLabel2)
																																		.add(
																																				jLabel1))
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED)
																														.add(
																																layout
																																		.createParallelGroup(
																																				org.jdesktop.layout.GroupLayout.TRAILING)
																																		.add(
																																				org.jdesktop.layout.GroupLayout.LEADING,
																																				layout
																																						.createSequentialGroup()
																																						.add(
																																								layout
																																										.createParallelGroup(
																																												org.jdesktop.layout.GroupLayout.LEADING,
																																												false)
																																										.add(
																																												org.jdesktop.layout.GroupLayout.TRAILING,
																																												jPasswordField1,
																																												0,
																																												0,
																																												Short.MAX_VALUE)
																																										.add(
																																												org.jdesktop.layout.GroupLayout.TRAILING,
																																												jTextField1,
																																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																												200,
																																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																																						.addPreferredGap(
																																								org.jdesktop.layout.LayoutStyle.RELATED))
																																		.add(
																																				org.jdesktop.layout.GroupLayout.LEADING,
																																				jPasswordField2,
																																				0,
																																				0,
																																				Short.MAX_VALUE))
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED))
																										.add(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												layout
																														.createSequentialGroup()
																														.add(
																																jLabel4)
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED)
																														.add(
																																jComboBox1,
																																0,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												14,
																												14,
																												14)
																										.add(
																												jLabel6)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jComboBox3,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												201,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				55,
																				Short.MAX_VALUE)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel5)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jComboBox2,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								jScrollPane1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								409,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
										.add(29, 29, 29)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(33, 33, 33)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				64,
																				64,
																				64)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jTextField1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jPasswordField1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel1)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel2)))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel3)
																						.add(
																								jPasswordField2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jComboBox1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								jLabel4))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel6)
																						.add(
																								jComboBox3,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				61,
																				Short.MAX_VALUE)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jButton1)
																						.add(
																								jButton3)
																						.add(
																								jButton2)))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel5)
																						.add(
																								jComboBox2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				226,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				57,
																				57,
																				57)))
										.add(39, 39, 39)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		//删除管理员
		String sqlLanguage = "DELETE tb_admin where adminName = ?";
		String[] psString = {oldName};
		if (psString == null) {
			return;
		}
		int res=JOptionPane.showConfirmDialog(null, "是否删除”"+oldName+"“的信息", "是否修改", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION){ 
        	int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
    		if (x > 0) {
    			
    			JOptionPane.showMessageDialog(null, "删除成功");
    			initTable();
    			jButton2.setEnabled(false);
    			jButton3.setEnabled(false);
    		}
        }else{
            return;
        }
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// 修改管理员
		String sqlLanguage = "UPDATE tb_admin SET adminName = ?,adminPassword = ?,adminLevel = ?, orgName = ? where adminName = ?";
		String[] psString = new String[5];
		System.arraycopy(getStrings(), 0, psString, 0, 4);
		psString[4] = oldName;
		if (psString == null) {
			return;
		}
		int res=JOptionPane.showConfirmDialog(null, "是否修改”"+oldName+"“的信息", "是否修改", JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION){ 
        	int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
    		if (x > 0) {
    			
    			JOptionPane.showMessageDialog(null, "修改成功");
    			initTable();
    			jButton2.setEnabled(false);
    			jButton3.setEnabled(false);
    		}
        }else{
            return;
        }		
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//添加管理员
		oldName = "防止重名没有作用DEFE32";
		String sqlLanguage = "INSERT tb_admin VALUES(?,?,?,?) ";
		String[] psString = getStrings();
		if (psString == null) {
			return;
		}
		int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
		if (x > 0) {
			JOptionPane.showMessageDialog(null, "插入成功");
			initTable();
			jButton2.setEnabled(false);
			jButton3.setEnabled(false);
		}
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		//点击表单获取数据
		int index = jTable1.getSelectedRow();
		jTextField1.setText((String) jTable1.getValueAt(index, 0));
		oldName = jTextField1.getText();
		otherFunction.setComboboxSelect(jComboBox1, (String) jTable1
				.getValueAt(index, 2));
		otherFunction.setComboboxSelect(jComboBox3, (String) jTable1
				.getValueAt(index, 3));
		jButton2.setEnabled(true);
		jButton3.setEnabled(true);
	}

	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {
		//修改查询box更新表单
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			String sqlLanguage = "SELECT * FROM tb_admin WHERE OrgName like ?";
			String[] psStrings = { (String) jComboBox2.getSelectedItem()};
			if (psStrings[0].equals("所有组织")) {
				psStrings[0] = "%";
			}
			otherFunction.selectTable(sqlLanguage, psStrings, jTable1);
		}

	}

	private void formInternalFrameClosed(
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenAdminManage(true);
	}

	private void formInternalFrameOpened(//初始化各类控件
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenAdminChange(false);
		initTable();
		String sqlLanguage1 = "SELECT OrgName FROM tb_organization";
		if (AdminLogin.getOrgName().equals("温州商学院")) {
			jComboBox2.removeAllItems();
			jComboBox2.addItem("所有组织");
			otherFunction.setComboBoxItem(sqlLanguage1, jComboBox2);					
		} else {
			System.out.println(AdminLogin.getOrgName()+"Dsdsdsds");
			jComboBox2.removeAllItems();
			jComboBox2.addItem(AdminLogin.getOrgName());
			jComboBox2.setEnabled(false);
		}
		jComboBox3.removeAllItems();
		otherFunction.setComboBoxItem(sqlLanguage1, jComboBox3);
		jButton2.setEnabled(false);
		jButton3.setEnabled(false);	
	}

	private String[] getStrings() {//获取增删改的内容
		String adminName, adminPassword, adminLevel, orgName, rePassword;
		adminName = jTextField1.getText();
		adminPassword = jPasswordField1.getText();
		rePassword = jPasswordField2.getText();
		
		if (adminName.equals("")) {
			JOptionPane.showMessageDialog(null, "用户名不能为空!!");
			return null;
		}
		if (adminPassword.equals("")) {
			JOptionPane.showMessageDialog(null, "密码不能为空!!");
			return null;
		}
		String sqlLanguage1 = "SELECT * FROM tb_admin WHERE AdminName = ?";
		String[] psString1 = { adminName };
		try {
			if (sqlFunction.doSqlSelect(sqlLanguage1, psString1, false).next()
					&& !adminName.equals(oldName)) {
				JOptionPane.showMessageDialog(null, "已经存在当前用户名!!");
				oldName=adminName;
				return null;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		if (!adminPassword.equals(rePassword)) {
			JOptionPane.showMessageDialog(null, "两次密码输入不一致!!");
			return null;
		}
		adminPassword = SHA1.encode(adminPassword);
		adminLevel = jComboBox1.getSelectedItem().toString();
		if (!AdminLogin.getAdminLevel().equals("高级管理员")&&adminLevel.equals("高级管理员")) {
			JOptionPane.showMessageDialog(null, "权限越级!您没有权限添加或修改为“高级管理员”");
			return null;
		}
		orgName = jComboBox3.getSelectedItem().toString();
		String[] psString = { adminName, adminPassword, adminLevel, orgName };
		return psString;
	}

	private void initTable() {
		String[] psStrings = { "", "" };
		if (AdminLogin.getOrgName().equals("温州商学院")) {
			psStrings[0] = "%";
		} else {
			psStrings[0] = AdminLogin.getOrgName();
			jComboBox2.setEnabled(false);
		}
		if (AdminLogin.getAdminLevel().equals("高级管理员")) {
			psStrings[1] = "%";
		} else {
			psStrings[1] = AdminLogin.getAdminLevel();
		}

		//		initTable(psStrings);
		String sqlLanguage = "SELECT * FROM tb_admin WHERE OrgName like ? and AdminLevel like ? ";
		otherFunction.selectTable(sqlLanguage, psStrings, jTable1);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}