/*
 * DepartManage.java
 *
 * Created on __DATE__, __TIME__
 */

package zjl.Frame;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.sun.org.apache.bcel.internal.generic.NEW;

import other.wzbcOrg.AdminLogin;
import other.wzbcOrg.OpenSituation;
import other.wzbcOrg.OtherFunction;
import other.wzbcOrg.SHA1;
import other.wzbcOrg.SqlFunction;

/**
 *
 * @author  __USER__
 */
public class DepartManage extends javax.swing.JInternalFrame {
	OtherFunction otherFunction = new OtherFunction();
	SqlFunction sqlFunction = new SqlFunction();

	/** Creates new form DepartManage */
	public DepartManage() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setMaximizable(true);
		setTitle("\u90e8\u95e8\u7ba1\u7406");
		addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			public void internalFrameActivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosed(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameClosed(evt);
			}

			public void internalFrameClosing(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeactivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeiconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameIconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameOpened(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameOpened(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "部门编号", "部门名称", "所属组织", "部门人数" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("\u88ab\u9009\u4e2d\u90e8\u95e8\u7f16\u53f7\uff1a");

		jLabel2.setText("\u7a7a");
		jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel3.setText("\u90e8\u95e8\u540d\u79f0\uff1a");

		jLabel4.setText("\u6240\u5c5e\u7ec4\u7ec7\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel5.setText("\u6240\u5c5e\u7ec4\u7ec7\u7b5b\u9009\uff1a");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox2.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox2ItemStateChanged(evt);
			}
		});

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/add.png"))); // NOI18N
		jButton1.setText("\u6dfb\u52a0\u90e8\u95e8");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/refresh.png"))); // NOI18N
		jButton2.setText("\u4fee\u6539\u90e8\u95e8");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/close.png"))); // NOI18N
		jButton3.setText("\u5220\u9664\u90e8\u95e8");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(44, 44, 44)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								jLabel4)
																						.add(
																								jLabel3)
																						.add(
																								jLabel1)
																						.add(
																								jLabel5))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jComboBox1,
																																0,
																																177,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.TRAILING,
																																jTextField1,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																177,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.TRAILING,
																																jComboBox2,
																																0,
																																177,
																																Short.MAX_VALUE))
																										.add(
																												63,
																												63,
																												63))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel2)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				389,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				75,
																				75,
																				75)
																		.add(
																				jButton1)
																		.add(
																				75,
																				75,
																				75)
																		.add(
																				jButton2)
																		.add(
																				68,
																				68,
																				68)
																		.add(
																				jButton3)))
										.add(33, 33, 33)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(44, 44, 44)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jComboBox2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								jLabel5))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				128,
																				Short.MAX_VALUE)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel1)
																						.add(
																								jLabel2))
																		.add(
																				22,
																				22,
																				22)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jTextField1,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												16,
																												16,
																												16)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.BASELINE)
																														.add(
																																jComboBox1,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																														.add(
																																jLabel4)))
																						.add(
																								jLabel3))
																		.add(
																				63,
																				63,
																				63))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				272,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton1).add(
																jButton3).add(
																jButton2)).add(
												39, 39, 39)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		int index = jTable1.getSelectedRow();
		jLabel2.setText((String) jTable1.getValueAt(index, 0));
		jTextField1.setText((String) jTable1.getValueAt(index, 1));
		otherFunction.setComboboxSelect(jComboBox1, (String) jTable1.getValueAt(index, 2));
		jButton2.setEnabled(true);
		jButton3.setEnabled(true);
	}

	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {
		//修改查询box更新表单
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			String sqlLanguage = "EXEC proc_SelectDepartWithCountPerson ?";
			String[] psStrings = { (String) jComboBox2.getSelectedItem() };
			System.out.println(psStrings[0]);
			if (psStrings[0].equals("所有组织")) {
				psStrings[0] = "%";
			}
			otherFunction.selectTable(sqlLanguage, psStrings, jTable1);
		}
	}

	private void formInternalFrameClosed(
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenDepartManage(false);
	}

	private void formInternalFrameOpened(//初始化控件
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenDepartManage(true);
		initTable();
		initCombobox();
		jButton2.setEnabled(false);
		jButton3.setEnabled(false);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		//删除部门
		String depId = jLabel2.getText();
		String sqlLanguage = "DELETE tb_department where depId = ?";
		String[] psString = { depId };
		int res = JOptionPane.showConfirmDialog(null, "是否删除编号为”" + depId
				+ "“的部门信息", "是否删除", JOptionPane.YES_NO_OPTION);
		if (res == JOptionPane.YES_OPTION) {
			String sqlLanguage1 = "SELECT * FROM tb_person where DepId = ?";
			String[] psString1 = { depId };
			try {
				if (sqlFunction.doSqlSelect(sqlLanguage1, psString1, false)
						.next()) {
					Object[] options = { "删除整个部门", "取消删除" };
					if (JOptionPane.showOptionDialog(null,
							"此操作将删除部门下的所有人员，您真的要删除编号为”" + depId + "“的部门信息吗？",
							"警告 ，这个部门下有人员存在", JOptionPane.DEFAULT_OPTION,
							JOptionPane.WARNING_MESSAGE, null, options,
							options[0]) == 0) {
						int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
						if (x > 0) {
							JOptionPane.showMessageDialog(null, "删除成功");
							initTable();
							initCombobox();
							jButton2.setEnabled(false);
							jButton3.setEnabled(false);
						}
					} else {
						return;
					}

				} else {
					int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
					if (x > 0) {

						JOptionPane.showMessageDialog(null, "删除成功");
						initTable();
						jButton2.setEnabled(false);
						jButton3.setEnabled(false);
					}
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
		} else {
			return;
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		//修改部门
		String depId = jLabel2.getText();
		String sqlLanguage = "UPDATE tb_department SET depName = ? , orgName = ? where depId = ?";
		String[] psString = new String[3];
		System.arraycopy(getStrings(), 0, psString, 0, 2);
		psString[2] = depId;
		if (psString == null) {
			return;
		}
		int res = JOptionPane.showConfirmDialog(null, "是否修改编号为”" + depId
				+ "“的部门的信息", "是否修改", JOptionPane.YES_NO_OPTION);
		if (res == JOptionPane.YES_OPTION) {
			int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
			if (x > 0) {
				JOptionPane.showMessageDialog(null, "修改成功");
				initTable();
				initCombobox();
				jButton2.setEnabled(false);
				jButton3.setEnabled(false);
			}
		} else {
			return;
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// 添加部门
		String sqlLanguage = "INSERT tb_department(depName,orgName) VALUES(?,?) ";
		String[] psString = getStrings();
		if (psString == null) {
			return;
		}
		System.out.println(psString[1]);
		int x = sqlFunction.doSqlUpdate(sqlLanguage, psString);
		if (x > 0) {
			JOptionPane.showMessageDialog(null, "插入成功");
			initTable();
			initCombobox();
			jButton2.setEnabled(false);
			jButton3.setEnabled(false);
		}
	}

	private String[] getStrings() {//获取增删改的内容
		String depName, orgName;
		depName = jTextField1.getText();
		if (depName.equals("")) {
			JOptionPane.showMessageDialog(null, "组织名不能为空!!");
			return null;
		}
		orgName = jComboBox1.getSelectedItem().toString();
		String[] psString = { depName, orgName };
		return psString;
	}

	private void initTable() {
		String[] psStrings = { "" };
		if (AdminLogin.getOrgName().equals("温州商学院")) {
			psStrings[0] = "%";
		} else {
			psStrings[0] = AdminLogin.getOrgName();
			jComboBox2.setEnabled(false);
		}
		String sqlLanguage = "EXEC proc_SelectDepartWithCountPerson ?";
		otherFunction.selectTable(sqlLanguage, psStrings, jTable1);
	}

	private void initCombobox() {
		String sqlLanguage1 = "SELECT DISTINCT OrgName FROM tb_department";
		if (AdminLogin.getOrgName().equals("温州商学院")) {
			jComboBox2.removeAllItems();
			jComboBox2.addItem("所有组织");
			otherFunction.setComboBoxItem(sqlLanguage1, jComboBox2);
		} else {
			jComboBox2.removeAllItems();
			jComboBox2.addItem(AdminLogin.getOrgName());
		}
		sqlLanguage1 = "SELECT  OrgName FROM tb_organization";
		jComboBox1.removeAllItems();
		otherFunction.setComboBoxItem(sqlLanguage1, jComboBox1);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}