/*
 * MessageSearch.java
 *
 * Created on __DATE__, __TIME__
 */

package zjl.Frame;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import other.wzbcOrg.AdminLogin;
import other.wzbcOrg.OpenSituation;
import other.wzbcOrg.OtherFunction;
import other.wzbcOrg.SqlFunction;

/**
 *
 * @author  __USER__
 */
public class MessageSearch extends javax.swing.JInternalFrame {
	SqlFunction sqlFunction = new SqlFunction();
	OtherFunction otherFunction = new OtherFunction();
	String oldID = "";
	String[] init = { "%", "%", "%", "%", "%", "%", "%" };

	/** Creates new form MessageSearch */
	public MessageSearch() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jComboBox3 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jLabel28 = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		jLabel32 = new javax.swing.JLabel();
		jComboBox4 = new javax.swing.JComboBox();
		jLabel34 = new javax.swing.JLabel();
		jLabel35 = new javax.swing.JLabel();
		jLabel37 = new javax.swing.JLabel();
		jLabel38 = new javax.swing.JLabel();
		jLabel39 = new javax.swing.JLabel();
		jLabel40 = new javax.swing.JLabel();
		jLabel41 = new javax.swing.JLabel();
		jLabel42 = new javax.swing.JLabel();
		jLabel43 = new javax.swing.JLabel();
		jLabel44 = new javax.swing.JLabel();
		jLabel46 = new javax.swing.JLabel();
		jLabel47 = new javax.swing.JLabel();
		jLabel48 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
			public void internalFrameActivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameClosed(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameClosed(evt);
			}

			public void internalFrameClosing(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeactivated(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameDeiconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameIconified(
					javax.swing.event.InternalFrameEvent evt) {
			}

			public void internalFrameOpened(
					javax.swing.event.InternalFrameEvent evt) {
				formInternalFrameOpened(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "部门编号", "部门名称", "所属组织", "部门人数" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jTable2
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] {

						}, new String[] { "学号", "姓名", "性别", "届次", "部门", "专业",
								"在职情况" }) {
					Class[] types = new Class[] { java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class,
							java.lang.String.class, java.lang.String.class };
					boolean[] canEdit = new boolean[] { false, false, false,
							false, false, false, false };

					public Class getColumnClass(int columnIndex) {
						return types[columnIndex];
					}

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable2MousePressed(evt);
			}
		});
		jScrollPane2.setViewportView(jTable2);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u7b5b\u9009\u5b57\u6bb5"));
		jPanel1.setToolTipText("");

		jLabel3.setText("\u5b66\u53f7\uff1a");

		jLabel4.setText("\u59d3\u540d\uff1a");

		jLabel5.setText("\u5c4a\u6b21\uff1a");

		jLabel6.setText("\u90e8\u95e8\uff1a");

		jLabel7.setText("\u4e13\u4e1a\uff1a");

		jCheckBox1.setText("\u5728\u804c");
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jCheckBox2.setText("\u79bb\u804c");
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox1ItemStateChanged(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox2.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox2ItemStateChanged(evt);
			}
		});

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox3.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox3ItemStateChanged(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel3)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				213,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel6)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox2,
																				0,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												23, Short.MAX_VALUE)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				45,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				204,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel7)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox3,
																				0,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.add(50, 50, 50)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel5)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				220,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jCheckBox1)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jCheckBox2)))
										.add(15, 15, 15)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(8, 8, 8)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.CENTER)
														.add(jLabel5)
														.add(
																jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel3)
														.add(
																jComboBox1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.CENTER)
																		.add(
																				jLabel6)
																		.add(
																				jComboBox2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.CENTER)
																		.add(
																				jComboBox3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				jLabel7))
														.add(
																jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.CENTER)
																		.add(
																				jCheckBox2)
																		.add(
																				jCheckBox1)))
										.addContainerGap(20, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel1.setText("\u7ec4\u7ec7\uff1a");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel2.setText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u90e8\u95e8");

		jLabel8.setText("\u603b\u5956\u52b1\u6b21\u6570\uff1a");

		jLabel9.setText("\u603b\u60e9\u7f5a\u6b21\u6570\uff1a");

		jLabel10.setText("\u603b\u8fdf\u5230\u6b21\u6570\uff1a");

		jLabel11.setText("\u603b\u8003\u52e4\u65f6\u957f\uff1a");

		jLabel12.setText("\u4e3e\u529e\u6d3b\u52a8\u6b21\u6570\uff1a");

		jLabel13.setText("\u5386\u5e74\u4efb\u804c\u4eba\u6570\uff1a");

		jLabel14.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel15.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel16.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel17.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel18.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel19.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel20.setText("\u59d3\u540d\uff1a");

		jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel21.setText("\u8bf7\u9009\u62e9\u5b66\u751f");

		jLabel22.setText("\u7f3a\u52e4\u6b21\u6570\uff1a");

		jLabel23.setText("\u8003\u52e4\u6b21\u6570\uff1a");

		jLabel24.setText("\u8003\u52e4\u603b\u65f6\u957f\uff1a");

		jLabel25.setText("\u83b7\u5956\u6b21\u6570\uff1a");

		jLabel26.setText("\u60e9\u7f5a\u6b21\u6570\uff1a");

		jLabel28.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel29.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel30.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel31.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel32.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox4.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox4ItemStateChanged(evt);
			}
		});

		jLabel34.setText("\u6240\u5c5e\u7ec4\u7ec7\u7b5b\u9009\uff1a");

		jLabel35.setText("\u603b\u8003\u52e4\u65f6\u957f\uff1a");

		jLabel37.setText("\u5386\u5e74\u4efb\u804c\u4eba\u6570\uff1a");

		jLabel38.setText("\u603b\u8fdf\u5230\u6b21\u6570\uff1a");

		jLabel39.setText("\u603b\u60e9\u7f5a\u6b21\u6570\uff1a");

		jLabel40.setText("\u603b\u5956\u52b1\u6b21\u6570\uff1a");

		jLabel41.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel42.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel43.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel44.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel46.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel47.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel47.setText("\u6b64\u7ec4\u7ec7\u7684\u90e8\u95e8\uff1a");

		jLabel48.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15));
		jLabel48.setText("\u8bf7\u9009\u62e9\u4e00\u4e2a\u90e8\u95e8");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ico/star.png"))); // NOI18N
		jButton1.setText("\u67e5\u770b\u5956\u60e9\u60c5\u51b5");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				47,
																				47,
																				47)
																		.add(
																				jLabel34)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jComboBox4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				128,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												55,
																												55,
																												55)
																										.add(
																												jLabel1,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												57,
																												Short.MAX_VALUE))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								layout
																										.createSequentialGroup()
																										.add(
																												15,
																												15,
																												15)
																										.add(
																												jLabel11,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												97,
																												Short.MAX_VALUE))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel12,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								112,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel13,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								112,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								layout
																										.createSequentialGroup()
																										.add(
																												15,
																												15,
																												15)
																										.add(
																												jLabel10,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												97,
																												Short.MAX_VALUE))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								layout
																										.createSequentialGroup()
																										.add(
																												15,
																												15,
																												15)
																										.add(
																												jLabel9,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												97,
																												Short.MAX_VALUE))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								layout
																										.createSequentialGroup()
																										.add(
																												15,
																												15,
																												15)
																										.add(
																												jLabel8,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												97,
																												Short.MAX_VALUE)))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								jLabel2,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								171,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.TRAILING,
																																false)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel19,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel18,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel17,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel16,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel15,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.add(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																jLabel14,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																96,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED,
																												82,
																												Short.MAX_VALUE)))
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												62,
																												62,
																												62)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel47)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jLabel48))
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.TRAILING)
																																						.add(
																																								jLabel37)
																																						.add(
																																								jLabel35)
																																						.add(
																																								jLabel38)
																																						.add(
																																								jLabel39)
																																						.add(
																																								jLabel40))
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.LEADING,
																																								false)
																																						.add(
																																								jLabel41,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel42,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel43,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel44,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel46,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								94,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				96,
																																				96,
																																				96)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.TRAILING)
																																						.add(
																																								jLabel22)
																																						.add(
																																								jLabel23)
																																						.add(
																																								jLabel24)
																																						.add(
																																								jLabel25)
																																						.add(
																																								jLabel26))
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.LEADING,
																																								false)
																																						.add(
																																								jLabel28,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel30,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								124,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel32,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel31,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								118,
																																								Short.MAX_VALUE)
																																						.add(
																																								jLabel29,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)))
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				142,
																																				142,
																																				142)
																																		.add(
																																				jLabel20)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jLabel21))))
																						.add(
																								org.jdesktop.layout.GroupLayout.TRAILING,
																								layout
																										.createSequentialGroup()
																										.add(
																												457,
																												457,
																												457)
																										.add(
																												jButton1,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.add(
																												19,
																												19,
																												19))))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jScrollPane2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				440,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(15, 15, 15)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				158,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								jLabel34)
																						.add(
																								jComboBox4,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane2,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				158,
																				Short.MAX_VALUE)
																		.add(
																				35,
																				35,
																				35)))
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				19,
																				19,
																				19)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.CENTER)
																						.add(
																								jLabel1,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jLabel2))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel13,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.add(
																												19,
																												19,
																												19)
																										.add(
																												jLabel12,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.add(
																												19,
																												19,
																												19)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel11,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.add(
																																				127,
																																				127,
																																				127))
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				39,
																																				39,
																																				39)
																																		.add(
																																				jLabel10,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.add(
																																				19,
																																				19,
																																				19)
																																		.add(
																																				jLabel9,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.add(
																																				19,
																																				19,
																																				19)
																																		.add(
																																				jLabel8,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.add(
																																				10,
																																				10,
																																				10))))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel14,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel15,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel16,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel17,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel18,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel19,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												30,
																												Short.MAX_VALUE))))
														.add(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.CENTER)
																						.add(
																								jLabel47)
																						.add(
																								jLabel48)
																						.add(
																								jLabel20)
																						.add(
																								jLabel21))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel24)
																														.add(
																																jLabel32,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																30,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel23)
																														.add(
																																jLabel31,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																30,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel22)
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel30,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				30,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.LEADING)
																																						.add(
																																								jLabel25)
																																						.add(
																																								jLabel29,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								30,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.LEADING)
																																						.add(
																																								jLabel28,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								30,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																						.add(
																																								jLabel26)))))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel37)
																														.add(
																																jLabel46,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																30,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																layout
																																		.createSequentialGroup()
																																		.add(
																																				jLabel44,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				30,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				layout
																																						.createParallelGroup(
																																								org.jdesktop.layout.GroupLayout.LEADING)
																																						.add(
																																								jLabel38)
																																						.add(
																																								jLabel43,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								30,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																														.add(
																																jLabel35))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel42,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																30,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																														.add(
																																jLabel39))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jLabel41,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																30,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																														.add(
																																jLabel40))))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jButton1)))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (jLabel21.getText().equals("请选择学生")) {
			JOptionPane.showMessageDialog(null, "请选择学生!!");
		}else{
			String sqlLanguage="SELECT RewardContent FROM tb_reward WHERE PersonNumber = ?";
			String[] psString={oldID};
			String rewardContent="奖励内容";
			ResultSet resultSet=sqlFunction.doSqlSelect(sqlLanguage, psString, false);
			try {
				while (resultSet.next()) {
					if (resultSet.getString(1)!=null&&!resultSet.getString(1).equals("")) {
						rewardContent=rewardContent+", "+resultSet.getString(1);
						System.out.println("dddeded");
					}		
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
			
			sqlLanguage="SELECT PunishContent FROM tb_reward WHERE PersonNumber = ?";
			String punishContent="处罚内容";
			resultSet=sqlFunction.doSqlSelect(sqlLanguage, psString, false);
			try {
				while (resultSet.next()) {
					if (resultSet.getString(1)!=null&&!resultSet.getString(1).equals("")) {
						punishContent=punishContent+", "+resultSet.getString(1);
					}
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
			
			JOptionPane.showMessageDialog(null,rewardContent+"\n"+punishContent,"学生 "
					+jLabel21.getText()+" 的奖惩信息", JOptionPane.DEFAULT_OPTION);
		}
	}

	private void jTable2MousePressed(java.awt.event.MouseEvent evt) {
		int index = jTable2.getSelectedRow();
		String sqlLanguage = "EXEC proc_SelectSearchStu ?";
		String[] psString = { (String) jTable2.getValueAt(index, 0) };
		oldID=(String) jTable2.getValueAt(index, 0);
		jLabel21.setText((String) jTable2.getValueAt(index, 1));
		ResultSet resultSet = sqlFunction.doSqlSelect(sqlLanguage, psString,
				false);
		try {
			if (resultSet.next()) {
				jLabel32.setText(" " + resultSet.getString(1));
				jLabel31.setText(" " + resultSet.getString(2));
				jLabel30.setText(" " + resultSet.getString(3));
				jLabel29.setText(" " + resultSet.getString(4));
				jLabel28.setText(" " + resultSet.getString(5));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		String sqlLanguage = "EXEC proc_SelectSearchDep ?";
		int index = jTable1.getSelectedRow();
		String[] psString = { (String) jTable1.getValueAt(index, 2) };
		jLabel2.setText((String) jTable1.getValueAt(index, 2));
		ResultSet resultSet = sqlFunction.doSqlSelect(sqlLanguage, psString,
				false);
		try {
			if (resultSet.next()) {
				jLabel14.setText(" " + resultSet.getString(1));
				jLabel15.setText(" " + resultSet.getString(2));
				jLabel16.setText(" " + resultSet.getString(3));
				jLabel17.setText(" " + resultSet.getString(4));
				jLabel18.setText(" " + resultSet.getString(5));
				jLabel19.setText(" " + resultSet.getString(6));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}

		sqlLanguage = "EXEC proc_SelectSearchDepID ?";
		psString[0] = (String) jTable1.getValueAt(index, 0);
		jLabel48.setText((String) jTable1.getValueAt(index, 1));
		resultSet = sqlFunction.doSqlSelect(sqlLanguage, psString, false);
		try {
			if (resultSet.next()) {
				jLabel46.setText(" " + resultSet.getString(1));
				jLabel44.setText(" " + resultSet.getString(2));
				jLabel43.setText(" " + resultSet.getString(3));
				jLabel42.setText(" " + resultSet.getString(4));
				jLabel41.setText(" " + resultSet.getString(5));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {
		//修改查询box更新表单
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			String sqlLanguage = "EXEC proc_SelectDepartWithCountPerson ?";
			String[] psStrings = { (String) jComboBox4.getSelectedItem() };
			if (psStrings[0].equals("所有组织")) {
				psStrings[0] = "%";
			}
			otherFunction.selectTable(sqlLanguage, psStrings, jTable1);
		}
	}

	private void formInternalFrameClosed(
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenMessgeSearch(false);
	}

	private void formInternalFrameOpened(
			javax.swing.event.InternalFrameEvent evt) {
		OpenSituation.setOpenMessgeSearch(true);
		initTable(init);
		initSelectCombobox();
		jTextField1.getDocument().addDocumentListener(new DocumentListener() {//对文本框进行文本变换监听
					public void changedUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}

					public void insertUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}

					public void removeUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}
				});
		jTextField2.getDocument().addDocumentListener(new DocumentListener() {//对文本框进行文本变换监听
					public void changedUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}

					public void insertUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}

					public void removeUpdate(DocumentEvent e) {
						initTable(getPsStrings());
					}
				});
	}

	private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			initTable(getPsStrings());
		}
	}

	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			initTable(getPsStrings());
		}
	}

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//不加这个会触发两次，（取消选择/选择）
			initTable(getPsStrings());
		}
	}

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		initTable(getPsStrings());
	}

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		initTable(getPsStrings());
	}

	private void initTable(String[] psStrings) {
		String[] psString = { "" };
		if (AdminLogin.getOrgName().equals("温州商学院")) {
			psStrings[0] = "%";
			psString[0] = "%";
		} else {
			psStrings[0] = AdminLogin.getOrgName();
			psString[0] = AdminLogin.getOrgName();
			jComboBox2.setEnabled(false);
			jComboBox4.setEnabled(false);
		}
		//		initTable(psStrings);
		String sqlLanguage = "SELECT PersonNumber,PersonName,PersonSex,PersonGrade,DepName,SpeName,PersonInJob "
				+ "FROM view_person_department "
				+ "where OrgName like ? and PersonNumber like ? and PersonName like ? and PersonGrade like ? "
				+ "and DepName like ? and SpeName like ? and PersonInJob like ? ";

		otherFunction.selectTable(sqlLanguage, psStrings, jTable2);
		for (int row = 0; row < jTable2.getRowCount(); row++) {
			if (jTable2.getValueAt(row, 2).equals("1")) {
				jTable2.setValueAt("男", row, 2);
			} else {
				jTable2.setValueAt("女", row, 2);
			}

			if (jTable2.getValueAt(row, 6).equals("1")) {
				jTable2.setValueAt("在职", row, 6);
			} else {
				jTable2.setValueAt("离职", row, 6);
			}
		}
		psString[0] = (String) jComboBox4.getSelectedItem();
		if (psString[0].equals("所有组织")) {
			psString[0] = "%";
		}
		sqlLanguage = "EXEC proc_SelectDepartWithCountPerson ?";
		otherFunction.selectTable(sqlLanguage, psString, jTable1);
	}

	private void initSelectCombobox() {
		String sqlLanguage1 = "SELECT DISTINCT PersonGrade FROM view_person_department ORDER BY PersonGrade";
		jComboBox1.removeAllItems();
		jComboBox1.addItem("所有届次");
		otherFunction.setComboBoxItem(sqlLanguage1, jComboBox1);
		sqlLanguage1 = "SELECT DISTINCT DepName FROM view_person_department ORDER BY DepName";
		jComboBox2.removeAllItems();
		jComboBox2.addItem("所有部门");
		otherFunction.setComboBoxItem(sqlLanguage1, jComboBox2);
		sqlLanguage1 = "SELECT DISTINCT SpeName FROM view_person_department ORDER BY SpeName";
		jComboBox3.removeAllItems();
		jComboBox3.addItem("所有专业");
		otherFunction.setComboBoxItem(sqlLanguage1, jComboBox3);

		sqlLanguage1 = "SELECT DISTINCT OrgName FROM tb_department";
		if (AdminLogin.getOrgName().equals("温州商学院") ) {
			jComboBox4.removeAllItems();
			jComboBox4.addItem("所有组织");
			otherFunction.setComboBoxItem(sqlLanguage1, jComboBox4);
		} else {
			jComboBox4.removeAllItems();
			jComboBox4.addItem(AdminLogin.getOrgName());
		}
	}

	private String[] getPsStrings() {
		String[] psStrings = { "%", "%", "%", "%", "%", "%", "%" };
		String personNumber = "%", personName = "%", personGrade = "%", depName = "%", speName = "%", personInJob = "%";
		if (!jTextField1.getText().equals("")) {
			personNumber = jTextField1.getText();
		}
		if (!jTextField2.getText().equals("")) {
			personName = jTextField2.getText();
		}
		if (!((String) jComboBox1.getSelectedItem()).equals("所有届次")) {
			personGrade = (String) jComboBox1.getSelectedItem();
		}
		if (!((String) jComboBox2.getSelectedItem()).equals("所有部门")) {
			depName = (String) jComboBox2.getSelectedItem();
		}
		if (!((String) jComboBox3.getSelectedItem()).equals("所有专业")) {
			speName = (String) jComboBox3.getSelectedItem();
		}
		if (jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
			personInJob = "%";
		} else if (jCheckBox1.isSelected()) {
			personInJob = "1";
		} else if (jCheckBox2.isSelected()) {
			personInJob = "0";
		}
		psStrings = new String[] { "%", personNumber, personName, personGrade,
				depName, speName, personInJob };
		return psStrings;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel40;
	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel42;
	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel jLabel44;
	private javax.swing.JLabel jLabel46;
	private javax.swing.JLabel jLabel47;
	private javax.swing.JLabel jLabel48;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}